//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.25 at 10:00:46 AM ART 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.zaubersoftware.leviathan.api.engine/ns/2011/01", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.zaubersoftware.leviathan.api.engine.impl.dto;
